### ISSUE TITLE
Persisting login user with gatsby

### ISSUE THREAD

**Issue by pszafer** [asyarb/react-use-googlelogin#19]
Hi,
Thank you for this component!
For logging in it works great, but in each refresh I'm getting logged out even though Storage is there.

First I tried samples from README.md, then I took some samples from nextjs ssr.

gatsby-ssr
```
export { wrapRootElement } from './src/apollo/wrap-root-element';
```

wrap-root-element
```
import React from 'react';
import ApolloWrapper from './client';
import { useGoogleLogin } from 'react-use-googlelogin'

const GoogleAuthContext = React.createContext() 

export const wrapRootElement = ({ element }) => (
  <GoogleAuthProvider>
    <ApolloWrapper>{element}</ApolloWrapper>
  </GoogleAuthProvider>
)


const GoogleAuthProvider = ({ children }) => {
  const {
    googleUser,
    isInitialized,
    grantOfflineAccess,
    signOut,
    isSignedIn,
    refreshUser,
  } = useGoogleLogin({
    clientId: process.env.GOOGLE_CLIENT_ID
  })

  const signInWithTokens = async () => {
    const code = await grantOfflineAccess()
    if (!code) return false

    const reqBody = {
      code,
    }
    await fetch('/api/googleTokens', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(reqBody),
    })

    return true
  }

  const fetchWithRefresh = async (
    input,
    init
  ) => {
    let accessToken = googleUser.accessToken
    const shouldRefreshToken =
      googleUser.expiresAt - 300 * 1000 - Date.now() <= 0

    if (shouldRefreshToken) {
      const tokenObj = await refreshUser()
      accessToken = tokenObj?.accessToken ?? accessToken
    }

    return fetch(input, {
      ...init,
      headers: {
        ...init?.headers,
        Authorization: `Bearer ${accessToken}`,
      },
    })
  }

  return (
    <GoogleAuthContext.Provider
      value={{
        googleUser,
        isInitialized,
        grantOfflineAccess,
        signOut,
        isSignedIn,
        refreshUser,
        signInWithTokens,
        fetchWithRefresh,
      }}>
      {children}
    </GoogleAuthContext.Provider>
  )
}

export const useGoogleAuth = () => React.useContext(GoogleAuthContext)

```

index.js
```
export default () => {
  const { signInWithTokens, signOut, isSignedIn, googleUser, isInitalized } = useGoogleAuth()
    if (isSignedIn) {
        return <button onClick={signOut}>Logout</button>;
    } else {
        return <button onClick={signInWithTokens}>Login</button>;
    }
}
```

`isSignedIn` is always false on each refresh.

**Comment by asyarb** [comment]
Hey @pszafer thanks for using the hook!

Is `isSignedIn` always `false` in your use case, even after React re-hydrates? After React re-hydrates, the hook should persist a previously authenticated user and `isSignedIn` should change to `true`.

Due to the way that Gatsby works, getting "true" SSR with Google authenticated content isn't possible. On the initial render, `isSignedIn` will always be `false` since Gatsby doesn't have access to `window.gapi`. For integrating with Gatsby, the `refreshing-tokens` example should "just work" (minus SSR of course) but I haven't formally tested it with Gatsby yet.

There's a [section in the readme](https://github.com/asyarb/react-use-googlelogin#dealing-with-a-flash-of-an-unauthenticated-view) that details some of the limitations of client-side only authentication. This section in conjunction with `isInitialized` may be helpful when using library with Gatsby.

**Comment by pszafer** [comment]
Thanks for such fast response!

`isSignedIn` is always false on refresh of page, until clicked 'singIn' button.

`refreshing-tokens` example is working same way minimal example is.
Based on this source: https://github.com/bennettrogers/redwood-googleauth/blob/master/web/src/contexts/GoogleAuthContext/GoogleAuthContext.js I managed to store access_token in Session storage and retrieve it after reload... but `googleUser` is always `undefined`.

Maybe you can look at this lib and example: https://github.com/Swizec/useAuth/tree/master/examples/useauth-gatsby 
with Auth0 is pretty easy to implement it in gatsby and it's working with SSR always (at least in my usage - Gatsby + extra Apollo fetching with JWT token).

**Comment by asyarb** [comment]
Hey @pszafer, looks like there was a regression in `0.12.4` that affected user persistence. Can you try updating to version `0.12.5` and let me know if you're still running into an issue?

I've also created a small [Gatsby example](https://github.com/asyarb/react-use-googlelogin/tree/master/examples/gatsby) that you can reference, but it's largely similar to what you have above.

Regarding the `useAuth` example, that library doesn't support "true" SSR as well. A snippet from [their docs](https://github.com/Swizec/useAuth#2-set-up-authprovider) confirms this:

> I recommend adding this around your root component. In Gatsby that's done in gatsby-browser.js and gatsby-ssr.js. Yes useAuth is built so it doesn't break server-side rendering. ✌️
>
> **But of course server-side "you" will always be logged out.**

Just like with this library, it isn't possible until after React hydrates at runtime to determine if a user is logged in. This is an inherent limitation with Gatsby since there isn't any way to have a server-side runtime in a purely build-time framework.

**Comment by pszafer** [comment]
0.12.5 is working perfectly fine. thanks!
