### ISSUE TITLE
Safari - Prevent Cross-Site Tracking

### ISSUE THREAD

**Issue by khaight** [asyarb/react-use-googlelogin#8]
I am using your library to implement google auth in my app.  It all works great except in safari. 

I am using `uxMode` redirect.  I can get it to work when I check the `Prevent cross-site tracking` in settings.

Do you know of any solution for this.  I don't think I can ask every user to change this setting.

Thanks in advance

**Comment by asyarb** [comment]
As far as I know, it looks like this issue exists upstream and is a limitation of google's `gapi` library which this hook uses under the hood.

You can see the open issue regarding this on their repo here below.

https://github.com/google/google-api-javascript-client/issues/589

Based on the discussion in the issue, it looks like Safari only supports setting `uxMode` being `popup` for the time being. Sorry for the trouble!

**Comment by khaight** [comment]
No worries, I just really appreciate you looking into it.  I notice sites like Asana are able to do this with redirect.  I have tried to poke around to understand how they do it, but no dice.

I was able to get the ‘id_token’ from the hash url but that token doesn’t include any basic profile information.  I was hoping to umber that token and be able to lookup the basic profile on my backend or front end app, but haven’t had any luck so far.  

Thanks again for your help.

**Comment by asyarb** [comment]
I did some digging into this, and wasn't able to reproduce the issue in Safari 13.0.5. Tried enabling and disabling `Prevent cross-site tracking`, emptying caches, to no avail. Out of curiosity, what version of Safari are you experiencing this on?
---

If you're able to get the `id_token` from the url hash, you may still be able to get some basic user information with it. Since it sounds like you have access to your backend, you could verify the `id_token` using their [Node library](https://github.com/googleapis/google-api-nodejs-client) and  make any requests for user data once verified.

Alternatively, you could try using Google's `tokeninfo` endpoint to verify the `id_token`. The response also includes some basic user data. Check out their docs on this endpoint [here](https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint).

**Comment by khaight** [comment]
I am using the same version of Safari.  Would you mind sharing your code over with me?
